all:
  hosts:
    installer:
      ansible_host: 10.80.40.10
    dns-ntp-0:
      ansible_host: 10.80.40.11
    dns-ntp-1:
      ansible_host: 10.80.50.11
    haproxy-0:
      ansible_host: 10.80.40.21
    haproxy-1:
      ansible_host: 10.80.50.21
    proxy-registry:
      ansible_host: 10.80.40.31
    nfs-0:
      ansible_host: 10.80.40.41
  children:
    dns_ntp:
      hosts:
        dns-ntp-0:
        dns-ntp-1:
    haproxy:
      hosts:
        haproxy-0:
        haproxy-1:
    proxy_registry:
      hosts:
        proxy-registry:
    nfs:
      hosts:
        nfs-0:
