#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$(cd -- "$SCRIPT_DIR/../terraform" && pwd)"
PLAN_FILE="$TERRAFORM_DIR/destroy.tfplan"
PLAN_META_FILE="$TERRAFORM_DIR/destroy.tfplan.meta"
AWS_PROFILE_NAME="${AWS_PROFILE_NAME:-openshift-lab}"
AWS_REGION_NAME="${AWS_REGION_NAME:-ap-northeast-3}"
DESTROY_APPLIED_FILE="${DESTROY_APPLIED_FILE:-$HOME/.config/openshift-upi-lab/destroy-applied.json}"
# shellcheck source=lib/safety-common.sh
source "$SCRIPT_DIR/lib/safety-common.sh"

operation='apply'
terminate_connection_id=''
if (($# == 2)) && [[ "$1" == '--terminate-connection' ]]; then
  operation='terminate-connection'
  terminate_connection_id="$2"
elif (($# != 0)); then
  printf 'Usage: %s [--terminate-connection cvpn-connection-id]\n' "${0##*/}" >&2
  exit 2
fi

if [[ "$operation" == 'terminate-connection' &&
      ! "$terminate_connection_id" =~ ^cvpn-connection-[0-9a-f]+$ ]]; then
  lab_safety_error 'The Client VPN ConnectionId format is invalid.'
fi

[[ -s "$PLAN_FILE" ]] || {
  printf 'ERROR: Missing saved destroy plan: %s\n' "$PLAN_FILE" >&2
  exit 1
}
[[ -s "$PLAN_META_FILE" ]] || {
  printf 'ERROR: Missing destroy plan guard metadata: %s\n' "$PLAN_META_FILE" >&2
  printf 'Run scripts/08-01-plan-destroy.sh again.\n' >&2
  exit 1
}

# Generated by scripts/08-01-plan-destroy.sh with shell-escaped scalar values.
ACCOUNT_ID=''
AWS_REGION=''
WORKSPACE=''
STATE_LINEAGE=''
STATE_SERIAL=''
PLAN_SHA256=''
DELETE_COUNT=''
# shellcheck disable=SC1090
source "$PLAN_META_FILE"

for guard_name in ACCOUNT_ID AWS_REGION WORKSPACE STATE_LINEAGE STATE_SERIAL PLAN_SHA256 DELETE_COUNT; do
  if [[ -z "${!guard_name:-}" ]]; then
    printf 'ERROR: Destroy plan guard metadata is obsolete or incomplete: %s\n' "$guard_name" >&2
    printf 'Run scripts/08-01-plan-destroy.sh again.\n' >&2
    exit 1
  fi
done

lab_validate_account_id "$ACCOUNT_ID" \
  || lab_safety_error 'Destroy Plan guard metadata contains an invalid account ID.'
[[ "$DELETE_COUNT" =~ ^[1-9][0-9]*$ ]] \
  || lab_safety_error 'Destroy Plan guard metadata contains an invalid delete count.'
registered_account="$(lab_resolve_expected_account_id legacy "$TERRAFORM_DIR" '')"
[[ "$registered_account" == "$ACCOUNT_ID" ]] \
  || lab_safety_error 'Destroy Plan account does not match the registered or state-recorded account.'
lab_assert_default_workspace "$TERRAFORM_DIR"
lab_assert_no_recovery_or_active_test

current_account="$(aws sts get-caller-identity --profile "$AWS_PROFILE_NAME" --query Account --output text)"
current_region="$(aws configure get region --profile "$AWS_PROFILE_NAME")"
current_workspace="$(terraform -chdir="$TERRAFORM_DIR" workspace show)"
current_state_identity="$(terraform -chdir="$TERRAFORM_DIR" state pull |
  jq -er '[.lineage, (.serial | tostring)] | @tsv')"
IFS=$'\t' read -r current_state_lineage current_state_serial <<<"$current_state_identity"
current_plan_sha256="$(sha256sum "$PLAN_FILE" | awk '{print $1}')"

guard_failure=0
[[ "$current_account" == "$ACCOUNT_ID" ]] || {
  printf 'ERROR: AWS account changed after the destroy Plan was saved.\n' >&2
  guard_failure=1
}
[[ "$current_region" == "$AWS_REGION" ]] || {
  printf 'ERROR: AWS region changed after the destroy Plan was saved.\n' >&2
  guard_failure=1
}
[[ "$current_workspace" == "$WORKSPACE" ]] || {
  printf 'ERROR: Terraform workspace changed after the destroy Plan was saved.\n' >&2
  guard_failure=1
}
[[ "$current_state_lineage" == "$STATE_LINEAGE" && "$current_state_serial" == "$STATE_SERIAL" ]] || {
  printf 'ERROR: Terraform state lineage or serial changed after the destroy Plan was saved.\n' >&2
  guard_failure=1
}
[[ "$current_plan_sha256" == "$PLAN_SHA256" ]] || {
  printf 'ERROR: The saved destroy Plan changed after its guard metadata was created.\n' >&2
  guard_failure=1
}

if ((guard_failure != 0)); then
  printf 'Discard this stale Plan with scripts/08-01-plan-destroy.sh --discard-saved-plan, then create a new Plan.\n' >&2
  exit 1
fi

plan_json="$(terraform -chdir="$TERRAFORM_DIR" show -json "$PLAN_FILE")"
actual_delete_count="$(jq -r '[.resource_changes[]? |
  select(.mode == "managed" and .change.actions == ["delete"])] | length' <<<"$plan_json")"
unexpected_action_count="$(jq -r '[.resource_changes[]? | select(.mode == "managed") |
  select(.change.actions != ["delete"] and .change.actions != ["no-op"])] | length' <<<"$plan_json")"
[[ "$actual_delete_count" == "$DELETE_COUNT" && "$unexpected_action_count" == 0 ]] \
  || lab_safety_error 'Saved destroy Plan no longer matches its guarded delete-only summary.'

client_vpn_endpoint_id="$(jq -r '.prior_state.values.root_module.resources[]? |
  select(.address == "aws_ec2_client_vpn_endpoint.lab[0]") | .values.id // empty' <<<"$plan_json")"
if [[ -n "$client_vpn_endpoint_id" ]]; then
  connection_json="$(aws ec2 describe-client-vpn-connections \
    --client-vpn-endpoint-id "$client_vpn_endpoint_id" \
    --profile "$AWS_PROFILE_NAME" --region "$AWS_REGION_NAME" --output json)"
  blocking_connections="$(jq -r '[.Connections[]? |
    select(.Status.Code != "terminated")] | length' <<<"$connection_json")"

  if [[ "$operation" == 'terminate-connection' ]]; then
    eligible_connection_count="$(jq -r --arg id "$terminate_connection_id" \
      '[.Connections[]? | select(.ConnectionId == $id and
        (.Status.Code == "active" or .Status.Code == "failed-to-terminate"))] | length' \
      <<<"$connection_json")"
    [[ "$eligible_connection_count" == 1 ]] \
      || lab_safety_error 'The specified ID is not exactly one active or failed-to-terminate connection on the guarded Endpoint.'

    printf 'Guarded Client VPN endpoint: %s\n' "$client_vpn_endpoint_id"
    printf 'ConnectionId\tStatus\tStatusMessage\tClientIp\tCommonName\tEstablishedTime\n'
    jq -r --arg id "$terminate_connection_id" '.Connections[]? |
      select(.ConnectionId == $id) |
      [(.ConnectionId // "-"), (.Status.Code // "-"), (.Status.Message // "-"),
       (.ClientIp // "-"), (.CommonName // "-"),
       (.ConnectionEstablishedTime // "-")] | @tsv' <<<"$connection_json"
    read -r -p "Type TERMINATE-$terminate_connection_id to continue: " CONFIRM
    if [[ "$CONFIRM" == "TERMINATE-$terminate_connection_id" ]]; then
      aws ec2 terminate-client-vpn-connections \
        --client-vpn-endpoint-id "$client_vpn_endpoint_id" \
        --connection-id "$terminate_connection_id" \
        --profile "$AWS_PROFILE_NAME" --region "$AWS_REGION_NAME"
      printf 'Termination was requested for %s.\n' "$terminate_connection_id"
      printf 'Wait until no non-terminated connection remains, then rerun this script without options.\n'
    else
      printf 'Client VPN connection termination cancelled.\n'
    fi
    exit 0
  fi

  [[ "$blocking_connections" == 0 ]] || {
    printf 'ERROR: %s non-terminated Client VPN connection(s) remain.\n' "$blocking_connections" >&2
    printf 'Client VPN endpoint: %s\n' "$client_vpn_endpoint_id" >&2
    printf 'ConnectionId\tStatus\tStatusMessage\tClientIp\tCommonName\tEstablishedTime\n' >&2
    jq -r '.Connections[]? |
      select(.Status.Code != "terminated") |
      [(.ConnectionId // "-"), (.Status.Code // "-"), (.Status.Message // "-"),
       (.ClientIp // "-"), (.CommonName // "-"),
       (.ConnectionEstablishedTime // "-")] | @tsv' \
      <<<"$connection_json" >&2
    printf 'Disconnect AWS Client VPN and wait while the status is terminating.\n' >&2
    printf 'For active or failed-to-terminate status after disconnect, follow docs/08-destroy.md section 5.\n' >&2
    printf 'The saved destroy Plan was not applied or changed; rerun this script after the session closes.\n' >&2
    exit 1
  }
  printf 'PASS: No non-terminated Client VPN connection remains.\n'
fi

[[ "$operation" == 'apply' ]] \
  || lab_safety_error 'The guarded destroy Plan does not contain a Client VPN endpoint.'

cd "$TERRAFORM_DIR"
printf 'Guarded delete count: %s\n' "$DELETE_COUNT"
read -r -p 'Type DESTROY-OPENSHIFT-UPI-LAB to continue: ' CONFIRM
if [[ "$CONFIRM" == 'DESTROY-OPENSHIFT-UPI-LAB' ]]; then
  unset TF_VAR_enable_client_vpn TF_VAR_client_vpn_server_certificate_arn \
    TF_VAR_enable_infrastructure_services TF_VAR_client_vpn_dns_servers \
    TF_VAR_enable_cluster_prerequisites TF_VAR_enable_cluster_nodes TF_VAR_enable_bootstrap \
    TF_VAR_rhcos_ami_id TF_VAR_ignition_base_url TF_VAR_ignition_spec_version TF_VAR_ignition_sha512
  terraform apply "$PLAN_FILE"
  rm -- "$PLAN_FILE" "$PLAN_META_FILE"
  remaining_managed="$(lab_managed_state_count_allow_absent "$TERRAFORM_DIR")"
  [[ "$remaining_managed" == 0 ]] \
    || lab_safety_error "Destroy applied but $remaining_managed managed resources remain in state."

  state_identity="$(terraform state pull | jq -er '[.lineage, (.serial | tostring)] | @tsv')"
  IFS=$'\t' read -r post_lineage post_serial <<<"$state_identity"
  install -d -m 700 "$(dirname -- "$DESTROY_APPLIED_FILE")"
  umask 077
  jq -n \
    --arg account_id "$ACCOUNT_ID" --arg region "$AWS_REGION" --arg workspace "$WORKSPACE" \
    --arg lineage "$post_lineage" --argjson serial "$post_serial" \
    --argjson deleted "$DELETE_COUNT" --arg applied_at "$(date -Iseconds)" \
    '{account_id:$account_id,region:$region,workspace:$workspace,state_lineage:$lineage,
      state_serial:$serial,deleted_resource_count:$deleted,applied_at:$applied_at}' \
    >"$DESTROY_APPLIED_FILE"
  chmod 600 "$DESTROY_APPLIED_FILE"
  printf 'Destroy completed. Removed the consumed Plan and guard metadata.\n'
  printf 'Destroy application marker: %s\n' "$DESTROY_APPLIED_FILE"
else
  printf 'Destroy cancelled.\n'
fi
